### PR TITLE
Pin the version of Release Drafter, but include in Dependabot

### PR DESCRIPTION
**Pull request by jglick**
https://github.com/release-drafter/release-drafter/pull/742 is significant.

### CODE REVIEW

**Review by jetersen — APPROVED** [review]
Glad you like the build improvement fix 👍

**Comment by jetersen** [comment]
You could properly add github actions to https://github.com/jenkinsci/archetypes/blob/master/.github/dependabot.yml as well it should detect this commons file as a github action workflow 🤔

**Comment by jglick** [comment]
@jetersen true, we _could_, though updates would not be exercised in CI, which makes me nervous.

**Comment by jetersen** [comment]
> @jetersen true, we _could_, though updates would not be exercised in CI, which makes me nervous.

These are simply pull requests, you could validate them by updating it on a plugin or two? 🤔

**Comment by jglick** [comment]
Perhaps. Will keep it in mind.

**Pull request merged**
