### PR TITLE
Update default Jenkinsfile to include Java 21

### PR DESCRIPTION
**Pull request by NotMyFault**
Fixes #34

### CODE REVIEW

**Review by basil — APPROVED** [review]
Can we get a spreadsheet going for implementing this in, say, the top 100 or 200 plugins at least? I'm willing to help

**Comment by NotMyFault** [comment]
> Can we get a spreadsheet going for implementing this in, say, the top 100 or 200 plugins at least? I'm willing to help

=> https://docs.google.com/spreadsheets/d/1RbeVLsyp03JP1qvM9jVcpZU2CPvOlI-Wffmez7u4IfY/edit?usp=sharing

**Comment by basil** [comment]
Commensurate with the effort that you and Mark have already expended, I have filled in about two dozen rows in the spreadsheet.

> => https://docs.google.com/spreadsheets/d/1RbeVLsyp03JP1qvM9jVcpZU2CPvOlI-Wffmez7u4IfY/edit?usp=sharing

A prerequisite for my approval of this pull request was an effort to migrate the ecosystem, but 170 rows of this spreadsheet are still red.

**Comment by jglick** [comment]
Rather recommend updating Linux from 17 to 21 but leaving Windows on 11, since we still support 11 (and I presume expect to still support it for some time), unless and until Jenkins core _drops_ 11 support and plugins begin picking up that baseline. Running all three seems unnecessary in terms of load on the CI system and I do not see much advantage—it is not very likely that a change would introduce a regression on 17 but not either 11 nor 21.

**Comment by basil** [comment]
That recommendation ignores the staggering implementation cost of multiple ecosystem-wide migrations:

https://github.com/jenkinsci/workflow-api-plugin/pull/299#issuecomment-1677873782

**Comment by jtnord** [comment]
The previous comment appears to asssume that you are doing that migration, however a plugin author can do that as and when their plugin bumps to a core requiring java 17 as a minium.  No staggering extra cost in incurred here, if an author is bumping core versions.

I agree with Jesse there is no reason to drop Java11 here.  Or if you are only interested in new plugins to use the same arguments against a plugin author in. Similar yet unrelated code changes

**Comment by jglick** [comment]
@jtnord can we move any subsequent discussion to #650? (I left comments in various places before finding the “root”, unfortunately leading to some split threads.) Or to the dev list if wider visibility seems warranted.

**Pull request merged**
