### PR TITLE
Simplify sample plugin POM with the BOM

### PR DESCRIPTION
**Pull request by jglick**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
i would wait a bit till the BOM concept is stabilized and has integration
testing in place

**Comment by jglick** [comment]
> has integration testing in place

It does integration testing internally. Or do you mean something beyond PCT?

**Comment by jglick** [comment]
Merging, but will hold off a bit on releasing to see how this plays out with @dependabot workflows. #71 etc. were correctly auto-closed. Will we get automatic notifications of new BOM versions? I am afraid that https://dependabot.com/docs/config-file/#allowed_updates does not seem to allow us to say that the allowed BOM must be 2.164.x, though arguably we should just update the sample to the current LTS anyway.

**Comment by jglick** [comment]
Also need to think about [JENKINS-58770](https://issues.jenkins-ci.org/browse/JENKINS-58770) before advertising this too widely.

**Pull request merged**
